feat: interactive testing
This allows to trigger an interactive shell after the test suite runs.
Note, that this of course breaks the output assertion.

Note, that `wash` is still very basic and, for example, path canonicalization
does not work on WASI out-of-the box (but will be implemented if required)

Example:
```
$ cargo test --features interactive -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.14s
     Running tests/wash.rs (target/debug/deps/wash-aaa75cf89309bc45)

running 2 tests
stdin:
ls /
echo 'test' > test
ls /
cat test
ls /dir

/ $ dir file
/ $ / $ dir file test
/ $ test
/ $ a.file b.dir
/ $ ls
dir file test
/ $ cd dir
/dir $ ls
a.file b.dir
/dir $ cd /
/ $ test tmpfs ... ok
stdin:
ls /
echo 'test' > test
cat test

/ $
/ $ / $ test
/ $ ls
test
/ $ cat test
test
/ $ cd dir
Error: failed to open `/dir`

Caused by:
    No such file or directory (os error 44)
/ $ exit
test wasi_sync_dir ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.09s

cargo test --features interactive -- --nocapture  35.86s user 0.28s system 119% cpu 30.282 total
```

Signed-off-by: Roman Volosatovs <roman@profian.com>